from extensions import db
from models import Medicine

MEDICINES = [
    # ═══════ ANTIBIOTICS ═══════
    {"name":"Amoxicillin 250mg","generic":"Amoxicillin","category":"antibiotic","unit":"capsule","strength":"250mg"},
    {"name":"Amoxicillin 500mg","generic":"Amoxicillin","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Amoxicillin 125mg Susp","generic":"Amoxicillin","category":"antibiotic","unit":"syrup","strength":"125mg/5ml"},
    {"name":"Amoxicillin 250mg Susp","generic":"Amoxicillin","category":"antibiotic","unit":"syrup","strength":"250mg/5ml"},
    {"name":"Co-Amoxiclav 156mg Susp","generic":"Amoxicillin + Clavulanic Acid","category":"antibiotic","unit":"syrup","strength":"156mg/5ml"},
    {"name":"Co-Amoxiclav 312mg Susp","generic":"Amoxicillin + Clavulanic Acid","category":"antibiotic","unit":"syrup","strength":"312mg/5ml"},
    {"name":"Co-Amoxiclav 375mg","generic":"Amoxicillin + Clavulanic Acid","category":"antibiotic","unit":"tablet","strength":"375mg"},
    {"name":"Co-Amoxiclav 625mg","generic":"Amoxicillin + Clavulanic Acid","category":"antibiotic","unit":"tablet","strength":"625mg"},
    {"name":"Co-Amoxiclav 1g","generic":"Amoxicillin + Clavulanic Acid","category":"antibiotic","unit":"tablet","strength":"1g"},
    {"name":"Co-Amoxiclav 1.2g Inj","generic":"Amoxicillin + Clavulanic Acid","category":"antibiotic","unit":"injection","strength":"1.2g"},
    {"name":"Ampicillin 500mg","generic":"Ampicillin","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Ampiclox 500mg","generic":"Ampicillin + Cloxacillin","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Ampiclox 250mg Susp","generic":"Ampicillin + Cloxacillin","category":"antibiotic","unit":"syrup","strength":"250mg/5ml"},
    {"name":"Ampiclox 500mg Inj","generic":"Ampicillin + Cloxacillin","category":"antibiotic","unit":"injection","strength":"500mg"},
    {"name":"Azithromycin 200mg Susp","generic":"Azithromycin","category":"antibiotic","unit":"syrup","strength":"200mg/5ml"},
    {"name":"Azithromycin 250mg","generic":"Azithromycin","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Azithromycin 500mg","generic":"Azithromycin","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Azithromycin 1g","generic":"Azithromycin","category":"antibiotic","unit":"tablet","strength":"1g"},
    {"name":"Ciprofloxacin 250mg","generic":"Ciprofloxacin","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Ciprofloxacin 500mg","generic":"Ciprofloxacin","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Ciprofloxacin 750mg","generic":"Ciprofloxacin","category":"antibiotic","unit":"tablet","strength":"750mg"},
    {"name":"Ciprofloxacin 200mg/100ml Inf","generic":"Ciprofloxacin","category":"antibiotic","unit":"other","strength":"200mg/100ml"},
    {"name":"Levofloxacin 250mg","generic":"Levofloxacin","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Levofloxacin 500mg","generic":"Levofloxacin","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Levofloxacin 750mg","generic":"Levofloxacin","category":"antibiotic","unit":"tablet","strength":"750mg"},
    {"name":"Moxifloxacin 400mg","generic":"Moxifloxacin","category":"antibiotic","unit":"tablet","strength":"400mg"},
    {"name":"Ofloxacin 200mg","generic":"Ofloxacin","category":"antibiotic","unit":"tablet","strength":"200mg"},
    {"name":"Ofloxacin 400mg","generic":"Ofloxacin","category":"antibiotic","unit":"tablet","strength":"400mg"},
    {"name":"Cefixime 100mg Susp","generic":"Cefixime","category":"antibiotic","unit":"syrup","strength":"100mg/5ml"},
    {"name":"Cefixime 200mg","generic":"Cefixime","category":"antibiotic","unit":"tablet","strength":"200mg"},
    {"name":"Cefixime 400mg","generic":"Cefixime","category":"antibiotic","unit":"tablet","strength":"400mg"},
    {"name":"Ceftriaxone 250mg Inj","generic":"Ceftriaxone","category":"antibiotic","unit":"injection","strength":"250mg"},
    {"name":"Ceftriaxone 500mg Inj","generic":"Ceftriaxone","category":"antibiotic","unit":"injection","strength":"500mg"},
    {"name":"Ceftriaxone 1g Inj","generic":"Ceftriaxone","category":"antibiotic","unit":"injection","strength":"1g"},
    {"name":"Ceftriaxone 2g Inj","generic":"Ceftriaxone","category":"antibiotic","unit":"injection","strength":"2g"},
    {"name":"Cefuroxime 250mg","generic":"Cefuroxime","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Cefuroxime 500mg","generic":"Cefuroxime","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Cefuroxime 750mg Inj","generic":"Cefuroxime","category":"antibiotic","unit":"injection","strength":"750mg"},
    {"name":"Cefaclor 250mg","generic":"Cefaclor","category":"antibiotic","unit":"capsule","strength":"250mg"},
    {"name":"Cefaclor 125mg Susp","generic":"Cefaclor","category":"antibiotic","unit":"syrup","strength":"125mg/5ml"},
    {"name":"Cefadroxil 500mg","generic":"Cefadroxil","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Cephalexin 250mg","generic":"Cephalexin","category":"antibiotic","unit":"capsule","strength":"250mg"},
    {"name":"Cephalexin 500mg","generic":"Cephalexin","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Cephalexin 125mg Susp","generic":"Cephalexin","category":"antibiotic","unit":"syrup","strength":"125mg/5ml"},
    {"name":"Cephalexin 250mg Susp","generic":"Cephalexin","category":"antibiotic","unit":"syrup","strength":"250mg/5ml"},
    {"name":"Cefpodoxime 100mg","generic":"Cefpodoxime","category":"antibiotic","unit":"tablet","strength":"100mg"},
    {"name":"Cefpodoxime 200mg","generic":"Cefpodoxime","category":"antibiotic","unit":"tablet","strength":"200mg"},
    {"name":"Cefdinir 300mg","generic":"Cefdinir","category":"antibiotic","unit":"capsule","strength":"300mg"},
    {"name":"Ceftazidime 1g Inj","generic":"Ceftazidime","category":"antibiotic","unit":"injection","strength":"1g"},
    {"name":"Cefoperazone 1g Inj","generic":"Cefoperazone","category":"antibiotic","unit":"injection","strength":"1g"},
    {"name":"Meropenem 500mg Inj","generic":"Meropenem","category":"antibiotic","unit":"injection","strength":"500mg"},
    {"name":"Meropenem 1g Inj","generic":"Meropenem","category":"antibiotic","unit":"injection","strength":"1g"},
    {"name":"Imipenem 500mg Inj","generic":"Imipenem + Cilastatin","category":"antibiotic","unit":"injection","strength":"500mg"},
    {"name":"Metronidazole 200mg","generic":"Metronidazole","category":"antibiotic","unit":"tablet","strength":"200mg"},
    {"name":"Metronidazole 400mg","generic":"Metronidazole","category":"antibiotic","unit":"tablet","strength":"400mg"},
    {"name":"Metronidazole 200mg/5ml Susp","generic":"Metronidazole","category":"antibiotic","unit":"syrup","strength":"200mg/5ml"},
    {"name":"Metronidazole 500mg/100ml Inf","generic":"Metronidazole","category":"antibiotic","unit":"other","strength":"500mg/100ml"},
    {"name":"Tinidazole 300mg","generic":"Tinidazole","category":"antibiotic","unit":"tablet","strength":"300mg"},
    {"name":"Tinidazole 500mg","generic":"Tinidazole","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Doxycycline 100mg","generic":"Doxycycline","category":"antibiotic","unit":"capsule","strength":"100mg"},
    {"name":"Clarithromycin 250mg","generic":"Clarithromycin","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Clarithromycin 500mg","generic":"Clarithromycin","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Clarithromycin 125mg Susp","generic":"Clarithromycin","category":"antibiotic","unit":"syrup","strength":"125mg/5ml"},
    {"name":"Erythromycin 250mg","generic":"Erythromycin","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Erythromycin 500mg","generic":"Erythromycin","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"Erythromycin 125mg Susp","generic":"Erythromycin","category":"antibiotic","unit":"syrup","strength":"125mg/5ml"},
    {"name":"Azithromycin Eye Drops","generic":"Azithromycin","category":"eye","unit":"drops","strength":"1%"},
    {"name":"Roxithromycin 150mg","generic":"Roxithromycin","category":"antibiotic","unit":"tablet","strength":"150mg"},
    {"name":"Roxithromycin 300mg","generic":"Roxithromycin","category":"antibiotic","unit":"tablet","strength":"300mg"},
    {"name":"Clindamycin 150mg","generic":"Clindamycin","category":"antibiotic","unit":"capsule","strength":"150mg"},
    {"name":"Clindamycin 300mg","generic":"Clindamycin","category":"antibiotic","unit":"capsule","strength":"300mg"},
    {"name":"Clindamycin 600mg Inj","generic":"Clindamycin","category":"antibiotic","unit":"injection","strength":"600mg"},
    {"name":"Clindamycin 1% Gel","generic":"Clindamycin","category":"antibiotic","unit":"cream","strength":"1%"},
    {"name":"Gentamicin 80mg Inj","generic":"Gentamicin","category":"antibiotic","unit":"injection","strength":"80mg"},
    {"name":"Gentamicin 0.3% Eye Drops","generic":"Gentamicin","category":"eye","unit":"drops","strength":"0.3%"},
    {"name":"Amikacin 500mg Inj","generic":"Amikacin","category":"antibiotic","unit":"injection","strength":"500mg"},
    {"name":"Vancomycin 500mg Inj","generic":"Vancomycin","category":"antibiotic","unit":"injection","strength":"500mg"},
    {"name":"Vancomycin 1g Inj","generic":"Vancomycin","category":"antibiotic","unit":"injection","strength":"1g"},
    {"name":"Linezolid 600mg","generic":"Linezolid","category":"antibiotic","unit":"tablet","strength":"600mg"},
    {"name":"Linezolid 600mg/300ml Inf","generic":"Linezolid","category":"antibiotic","unit":"other","strength":"600mg/300ml"},
    {"name":"Nitrofurantoin 100mg","generic":"Nitrofurantoin","category":"antibiotic","unit":"capsule","strength":"100mg"},
    {"name":"Sulfamethoxazole/Trimethoprim 400/80mg","generic":"Co-Trimoxazole","category":"antibiotic","unit":"tablet","strength":"400/80mg"},
    {"name":"Sulfamethoxazole/Trimethoprim 200/40mg Susp","generic":"Co-Trimoxazole","category":"antibiotic","unit":"syrup","strength":"200/40mg/5ml"},
    {"name":"Flucoxacillin 250mg","generic":"Flucoxacillin","category":"antibiotic","unit":"capsule","strength":"250mg"},
    {"name":"Flucoxacillin 500mg","generic":"Flucoxacillin","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Flucoxacillin 125mg Susp","generic":"Flucoxacillin","category":"antibiotic","unit":"syrup","strength":"125mg/5ml"},
    {"name":"Cloxacillin 250mg","generic":"Cloxacillin","category":"antibiotic","unit":"capsule","strength":"250mg"},
    {"name":"Cloxacillin 500mg","generic":"Cloxacillin","category":"antibiotic","unit":"capsule","strength":"500mg"},
    {"name":"Penicillin V 250mg","generic":"Phenoxymethylpenicillin","category":"antibiotic","unit":"tablet","strength":"250mg"},
    {"name":"Benzathine Penicillin 1.2MU Inj","generic":"Benzathine Penicillin","category":"antibiotic","unit":"injection","strength":"1.2MU"},
    {"name":"Piperacillin/Tazobactam 4.5g Inj","generic":"Piperacillin + Tazobactam","category":"antibiotic","unit":"injection","strength":"4.5g"},
    {"name":"Colistin 150mg Inj","generic":"Colistimethate","category":"antibiotic","unit":"injection","strength":"150mg"},
    {"name":"Rifampicin 450mg","generic":"Rifampicin","category":"antibiotic","unit":"capsule","strength":"450mg"},
    {"name":"Isoniazid 100mg","generic":"Isoniazid","category":"antibiotic","unit":"tablet","strength":"100mg"},
    {"name":"Ethambutol 400mg","generic":"Ethambutol","category":"antibiotic","unit":"tablet","strength":"400mg"},
    {"name":"Pyrazinamide 500mg","generic":"Pyrazinamide","category":"antibiotic","unit":"tablet","strength":"500mg"},
    {"name":"AKT-4 (RHZE)","generic":"Rifampicin+Isoniazid+Pyrazinamide+Ethambutol","category":"antibiotic","unit":"tablet","strength":"RHZE"},
    {"name":"AKT-3 (RHE)","generic":"Rifampicin+Isoniazid+Ethambutol","category":"antibiotic","unit":"tablet","strength":"RHE"},

    # ═══════ ANALGESICS & ANTIPYRETICS ═══════
    {"name":"Paracetamol 120mg Susp","generic":"Paracetamol","category":"analgesic","unit":"syrup","strength":"120mg/5ml"},
    {"name":"Paracetamol 250mg Susp","generic":"Paracetamol","category":"analgesic","unit":"syrup","strength":"250mg/5ml"},
    {"name":"Paracetamol 500mg","generic":"Paracetamol","category":"analgesic","unit":"tablet","strength":"500mg"},
    {"name":"Paracetamol 650mg","generic":"Paracetamol","category":"analgesic","unit":"tablet","strength":"650mg"},
    {"name":"Paracetamol 1g","generic":"Paracetamol","category":"analgesic","unit":"tablet","strength":"1g"},
    {"name":"Paracetamol 10mg/ml Inf","generic":"Paracetamol","category":"analgesic","unit":"other","strength":"10mg/ml"},
    {"name":"Ibuprofen 200mg","generic":"Ibuprofen","category":"analgesic","unit":"tablet","strength":"200mg"},
    {"name":"Ibuprofen 400mg","generic":"Ibuprofen","category":"analgesic","unit":"tablet","strength":"400mg"},
    {"name":"Ibuprofen 600mg","generic":"Ibuprofen","category":"analgesic","unit":"tablet","strength":"600mg"},
    {"name":"Ibuprofen 100mg Susp","generic":"Ibuprofen","category":"analgesic","unit":"syrup","strength":"100mg/5ml"},
    {"name":"Ibuprofen 200mg Susp","generic":"Ibuprofen","category":"analgesic","unit":"syrup","strength":"200mg/5ml"},
    {"name":"Diclofenac Sodium 50mg","generic":"Diclofenac Sodium","category":"analgesic","unit":"tablet","strength":"50mg"},
    {"name":"Diclofenac Sodium 75mg Inj","generic":"Diclofenac Sodium","category":"analgesic","unit":"injection","strength":"75mg"},
    {"name":"Diclofenac Potassium 50mg","generic":"Diclofenac Potassium","category":"analgesic","unit":"tablet","strength":"50mg"},
    {"name":"Diclofenac 1% Gel","generic":"Diclofenac","category":"analgesic","unit":"cream","strength":"1%"},
    {"name":"Naproxen 250mg","generic":"Naproxen","category":"analgesic","unit":"tablet","strength":"250mg"},
    {"name":"Naproxen 500mg","generic":"Naproxen","category":"analgesic","unit":"tablet","strength":"500mg"},
    {"name":"Mefenamic Acid 250mg","generic":"Mefenamic Acid","category":"analgesic","unit":"tablet","strength":"250mg"},
    {"name":"Mefenamic Acid 500mg","generic":"Mefenamic Acid","category":"analgesic","unit":"tablet","strength":"500mg"},
    {"name":"Mefenamic Acid 50mg/5ml Susp","generic":"Mefenamic Acid","category":"analgesic","unit":"syrup","strength":"50mg/5ml"},
    {"name":"Ketorolac 10mg","generic":"Ketorolac","category":"analgesic","unit":"tablet","strength":"10mg"},
    {"name":"Ketorolac 30mg Inj","generic":"Ketorolac","category":"analgesic","unit":"injection","strength":"30mg"},
    {"name":"Indomethacin 25mg","generic":"Indomethacin","category":"analgesic","unit":"capsule","strength":"25mg"},
    {"name":"Piroxicam 20mg","generic":"Piroxicam","category":"analgesic","unit":"capsule","strength":"20mg"},
    {"name":"Flurbiprofen 100mg","generic":"Flurbiprofen","category":"analgesic","unit":"tablet","strength":"100mg"},
    {"name":"Tramadol 50mg","generic":"Tramadol","category":"analgesic","unit":"capsule","strength":"50mg"},
    {"name":"Tramadol 100mg","generic":"Tramadol","category":"analgesic","unit":"tablet","strength":"100mg"},
    {"name":"Tramadol 50mg Inj","generic":"Tramadol","category":"analgesic","unit":"injection","strength":"50mg"},
    {"name":"Tramadol + Paracetamol 37.5/325mg","generic":"Tramadol + Paracetamol","category":"analgesic","unit":"tablet","strength":"37.5/325mg"},
    {"name":"Pregabalin 75mg","generic":"Pregabalin","category":"cns","unit":"capsule","strength":"75mg"},
    {"name":"Pregabalin 150mg","generic":"Pregabalin","category":"cns","unit":"capsule","strength":"150mg"},
    {"name":"Gabapentin 100mg","generic":"Gabapentin","category":"cns","unit":"capsule","strength":"100mg"},
    {"name":"Gabapentin 300mg","generic":"Gabapentin","category":"cns","unit":"capsule","strength":"300mg"},
    {"name":"Carbamazepine 200mg","generic":"Carbamazepine","category":"cns","unit":"tablet","strength":"200mg"},
    {"name":"Valproic Acid 200mg","generic":"Valproic Acid","category":"cns","unit":"tablet","strength":"200mg"},
    {"name":"Valproic Acid 500mg","generic":"Valproic Acid","category":"cns","unit":"tablet","strength":"500mg"},
    {"name":"Phenytoin 100mg","generic":"Phenytoin","category":"cns","unit":"tablet","strength":"100mg"},
    {"name":"Phenytoin 250mg Inj","generic":"Phenytoin","category":"cns","unit":"injection","strength":"250mg"},

    # ═══════ ANTIHISTAMINES & ALLERGY ═══════
    {"name":"Cetirizine 10mg","generic":"Cetirizine","category":"antihistamine","unit":"tablet","strength":"10mg"},
    {"name":"Cetirizine 1mg/ml Syrup","generic":"Cetirizine","category":"antihistamine","unit":"syrup","strength":"1mg/ml"},
    {"name":"Levocetirizine 5mg","generic":"Levocetirizine","category":"antihistamine","unit":"tablet","strength":"5mg"},
    {"name":"Levocetirizine 2.5mg/5ml Syrup","generic":"Levocetirizine","category":"antihistamine","unit":"syrup","strength":"2.5mg/5ml"},
    {"name":"Fexofenadine 120mg","generic":"Fexofenadine","category":"antihistamine","unit":"tablet","strength":"120mg"},
    {"name":"Fexofenadine 180mg","generic":"Fexofenadine","category":"antihistamine","unit":"tablet","strength":"180mg"},
    {"name":"Loratadine 10mg","generic":"Loratadine","category":"antihistamine","unit":"tablet","strength":"10mg"},
    {"name":"Desloratadine 5mg","generic":"Desloratadine","category":"antihistamine","unit":"tablet","strength":"5mg"},
    {"name":"Chlorpheniramine 4mg","generic":"Chlorpheniramine","category":"antihistamine","unit":"tablet","strength":"4mg"},
    {"name":"Hydroxyzine 25mg","generic":"Hydroxyzine","category":"antihistamine","unit":"tablet","strength":"25mg"},
    {"name":"Ketotifen 1mg","generic":"Ketotifen","category":"antihistamine","unit":"tablet","strength":"1mg"},
    {"name":"Ketotifen Syrup","generic":"Ketotifen","category":"antihistamine","unit":"syrup","strength":"1mg/5ml"},
    {"name":"Montelukast 4mg Chewable","generic":"Montelukast","category":"respiratory","unit":"tablet","strength":"4mg"},
    {"name":"Montelukast 5mg Chewable","generic":"Montelukast","category":"respiratory","unit":"tablet","strength":"5mg"},
    {"name":"Montelukast 10mg","generic":"Montelukast","category":"respiratory","unit":"tablet","strength":"10mg"},
    {"name":"Montelukast + Levocetirizine","generic":"Montelukast + Levocetirizine","category":"respiratory","unit":"tablet","strength":"10/5mg"},

    # ═══════ RESPIRATORY ═══════
    {"name":"Salbutamol 2mg","generic":"Salbutamol","category":"respiratory","unit":"tablet","strength":"2mg"},
    {"name":"Salbutamol 4mg","generic":"Salbutamol","category":"respiratory","unit":"tablet","strength":"4mg"},
    {"name":"Salbutamol 2mg/5ml Syrup","generic":"Salbutamol","category":"respiratory","unit":"syrup","strength":"2mg/5ml"},
    {"name":"Salbutamol Inhaler 100mcg","generic":"Salbutamol","category":"respiratory","unit":"other","strength":"100mcg/dose"},
    {"name":"Salbutamol 0.5mg Respules","generic":"Salbutamol","category":"respiratory","unit":"other","strength":"0.5mg/2.5ml"},
    {"name":"Salbutamol + Ipratropium Respules","generic":"Salbutamol + Ipratropium","category":"respiratory","unit":"other","strength":"0.5/0.25mg"},
    {"name":"Budesonide 100mcg Inhaler","generic":"Budesonide","category":"respiratory","unit":"other","strength":"100mcg/dose"},
    {"name":"Budesonide 200mcg Inhaler","generic":"Budesonide","category":"respiratory","unit":"other","strength":"200mcg/dose"},
    {"name":"Budesonide 0.5mg Respules","generic":"Budesonide","category":"respiratory","unit":"other","strength":"0.5mg/2ml"},
    {"name":"Budesonide 1mg Respules","generic":"Budesonide","category":"respiratory","unit":"other","strength":"1mg/2ml"},
    {"name":"Fluticasone 125mcg Inhaler","generic":"Fluticasone","category":"respiratory","unit":"other","strength":"125mcg/dose"},
    {"name":"Fluticasone 250mcg Inhaler","generic":"Fluticasone","category":"respiratory","unit":"other","strength":"250mcg/dose"},
    {"name":"Salmeterol + Fluticasone 50/250mcg","generic":"Salmeterol + Fluticasone","category":"respiratory","unit":"other","strength":"50/250mcg"},
    {"name":"Salmeterol + Fluticasone 50/500mcg","generic":"Salmeterol + Fluticasone","category":"respiratory","unit":"other","strength":"50/500mcg"},
    {"name":"Tiotropium 18mcg Inhaler","generic":"Tiotropium","category":"respiratory","unit":"other","strength":"18mcg"},
    {"name":"Theophylline 200mg SR","generic":"Theophylline","category":"respiratory","unit":"tablet","strength":"200mg"},
    {"name":"Theophylline 300mg SR","generic":"Theophylline","category":"respiratory","unit":"tablet","strength":"300mg"},
    {"name":"Doxofylline 400mg","generic":"Doxofylline","category":"respiratory","unit":"tablet","strength":"400mg"},
    {"name":"Ambroxol 30mg","generic":"Ambroxol","category":"respiratory","unit":"tablet","strength":"30mg"},
    {"name":"Ambroxol 75mg SR","generic":"Ambroxol","category":"respiratory","unit":"capsule","strength":"75mg"},
    {"name":"Ambroxol 15mg/5ml Syrup","generic":"Ambroxol","category":"respiratory","unit":"syrup","strength":"15mg/5ml"},
    {"name":"Bromhexine 8mg","generic":"Bromhexine","category":"respiratory","unit":"tablet","strength":"8mg"},
    {"name":"Acetylcysteine 200mg","generic":"Acetylcysteine","category":"respiratory","unit":"tablet","strength":"200mg"},
    {"name":"Acetylcysteine 600mg","generic":"Acetylcysteine","category":"respiratory","unit":"tablet","strength":"600mg"},
    {"name":"Acetylcysteine 300mg/3ml Inj","generic":"Acetylcysteine","category":"respiratory","unit":"injection","strength":"300mg/3ml"},
    {"name":"Dextromethorphan 15mg/5ml Syrup","generic":"Dextromethorphan","category":"respiratory","unit":"syrup","strength":"15mg/5ml"},
    {"name":"Guaifenesin 100mg/5ml Syrup","generic":"Guaifenesin","category":"respiratory","unit":"syrup","strength":"100mg/5ml"},
    {"name":"Pseudoephedrine 60mg","generic":"Pseudoephedrine","category":"respiratory","unit":"tablet","strength":"60mg"},
    {"name":"Pseudoephedrine 120mg SR","generic":"Pseudoephedrine","category":"respiratory","unit":"tablet","strength":"120mg"},
    {"name":"Chlorpheniramine + Pseudoephedrine","generic":"Chlorpheniramine + Pseudoephedrine","category":"respiratory","unit":"tablet","strength":"4/60mg"},
    {"name":"Levosalbutamol 0.63mg Respules","generic":"Levosalbutamol","category":"respiratory","unit":"other","strength":"0.63mg/2.5ml"},

    # ═══════ STEROIDS ═══════
    {"name":"Prednisolone 5mg","generic":"Prednisolone","category":"steroid","unit":"tablet","strength":"5mg"},
    {"name":"Prednisolone 15mg/5ml Syrup","generic":"Prednisolone","category":"steroid","unit":"syrup","strength":"15mg/5ml"},
    {"name":"Prednisolone 30mg","generic":"Prednisolone","category":"steroid","unit":"tablet","strength":"30mg"},
    {"name":"Prednisone 5mg","generic":"Prednisone","category":"steroid","unit":"tablet","strength":"5mg"},
    {"name":"Dexamethasone 0.5mg","generic":"Dexamethasone","category":"steroid","unit":"tablet","strength":"0.5mg"},
    {"name":"Dexamethasone 4mg Inj","generic":"Dexamethasone","category":"steroid","unit":"injection","strength":"4mg"},
    {"name":"Dexamethasone 8mg Inj","generic":"Dexamethasone","category":"steroid","unit":"injection","strength":"8mg"},
    {"name":"Hydrocortisone 100mg Inj","generic":"Hydrocortisone","category":"steroid","unit":"injection","strength":"100mg"},
    {"name":"Methylprednisolone 16mg","generic":"Methylprednisolone","category":"steroid","unit":"tablet","strength":"16mg"},
    {"name":"Methylprednisolone 40mg Inj","generic":"Methylprednisolone","category":"steroid","unit":"injection","strength":"40mg"},
    {"name":"Methylprednisolone 500mg Inj","generic":"Methylprednisolone","category":"steroid","unit":"injection","strength":"500mg"},
    {"name":"Betamethasone 0.5mg","generic":"Betamethasone","category":"steroid","unit":"tablet","strength":"0.5mg"},
    {"name":"Triamcinolone 40mg Inj","generic":"Triamcinolone","category":"steroid","unit":"injection","strength":"40mg"},
    {"name":"Beclomethasone Inhaler","generic":"Beclomethasone","category":"respiratory","unit":"other","strength":"50mcg/dose"},

    # ═══════ GI & ANTIEMETICS ═══════
    {"name":"Ondansetron 2mg/5ml Syrup","generic":"Ondansetron","category":"antiemetic","unit":"syrup","strength":"2mg/5ml"},
    {"name":"Ondansetron 4mg","generic":"Ondansetron","category":"antiemetic","unit":"tablet","strength":"4mg"},
    {"name":"Ondansetron 8mg","generic":"Ondansetron","category":"antiemetic","unit":"tablet","strength":"8mg"},
    {"name":"Ondansetron 4mg Inj","generic":"Ondansetron","category":"antiemetic","unit":"injection","strength":"4mg"},
    {"name":"Ondansetron 8mg Inj","generic":"Ondansetron","category":"antiemetic","unit":"injection","strength":"8mg"},
    {"name":"Domperidone 10mg","generic":"Domperidone","category":"antiemetic","unit":"tablet","strength":"10mg"},
    {"name":"Domperidone 1mg/ml Syrup","generic":"Domperidone","category":"antiemetic","unit":"syrup","strength":"1mg/ml"},
    {"name":"Domperidone 30mg SR","generic":"Domperidone","category":"antiemetic","unit":"capsule","strength":"30mg"},
    {"name":"Metoclopramide 10mg","generic":"Metoclopramide","category":"antiemetic","unit":"tablet","strength":"10mg"},
    {"name":"Metoclopramide 5mg/5ml Syrup","generic":"Metoclopramide","category":"antiemetic","unit":"syrup","strength":"5mg/5ml"},
    {"name":"Metoclopramide 10mg Inj","generic":"Metoclopramide","category":"antiemetic","unit":"injection","strength":"10mg"},
    {"name":"Prochlorperazine 5mg","generic":"Prochlorperazine","category":"antiemetic","unit":"tablet","strength":"5mg"},
    {"name":"Omeprazole 10mg","generic":"Omeprazole","category":"gi","unit":"capsule","strength":"10mg"},
    {"name":"Omeprazole 20mg","generic":"Omeprazole","category":"gi","unit":"capsule","strength":"20mg"},
    {"name":"Omeprazole 40mg","generic":"Omeprazole","category":"gi","unit":"capsule","strength":"40mg"},
    {"name":"Omeprazole 20mg Inj","generic":"Omeprazole","category":"gi","unit":"injection","strength":"20mg"},
    {"name":"Esomeprazole 20mg","generic":"Esomeprazole","category":"gi","unit":"tablet","strength":"20mg"},
    {"name":"Esomeprazole 40mg","generic":"Esomeprazole","category":"gi","unit":"tablet","strength":"40mg"},
    {"name":"Esomeprazole 40mg Inj","generic":"Esomeprazole","category":"gi","unit":"injection","strength":"40mg"},
    {"name":"Pantoprazole 20mg","generic":"Pantoprazole","category":"gi","unit":"tablet","strength":"20mg"},
    {"name":"Pantoprazole 40mg","generic":"Pantoprazole","category":"gi","unit":"tablet","strength":"40mg"},
    {"name":"Pantoprazole 40mg Inj","generic":"Pantoprazole","category":"gi","unit":"injection","strength":"40mg"},
    {"name":"Rabeprazole 20mg","generic":"Rabeprazole","category":"gi","unit":"tablet","strength":"20mg"},
    {"name":"Lansoprazole 30mg","generic":"Lansoprazole","category":"gi","unit":"capsule","strength":"30mg"},
    {"name":"Ranitidine 150mg","generic":"Ranitidine","category":"gi","unit":"tablet","strength":"150mg"},
    {"name":"Ranitidine 300mg","generic":"Ranitidine","category":"gi","unit":"tablet","strength":"300mg"},
    {"name":"Ranitidine 75mg/5ml Syrup","generic":"Ranitidine","category":"gi","unit":"syrup","strength":"75mg/5ml"},
    {"name":"Ranitidine 50mg Inj","generic":"Ranitidine","category":"gi","unit":"injection","strength":"50mg"},
    {"name":"Famotidine 20mg","generic":"Famotidine","category":"gi","unit":"tablet","strength":"20mg"},
    {"name":"Famotidine 40mg","generic":"Famotidine","category":"gi","unit":"tablet","strength":"40mg"},
    {"name":"Cimetidine 200mg","generic":"Cimetidine","category":"gi","unit":"tablet","strength":"200mg"},
    {"name":"Sucralfate 1g","generic":"Sucralfate","category":"gi","unit":"tablet","strength":"1g"},
    {"name":"Sucralfate 1g/5ml Susp","generic":"Sucralfate","category":"gi","unit":"syrup","strength":"1g/5ml"},
    {"name":"Loperamide 2mg","generic":"Loperamide","category":"gi","unit":"capsule","strength":"2mg"},
    {"name":"Loperamide 1mg/5ml Syrup","generic":"Loperamide","category":"gi","unit":"syrup","strength":"1mg/5ml"},
    {"name":"Hyoscine Butylbromide 10mg","generic":"Hyoscine Butylbromide","category":"gi","unit":"tablet","strength":"10mg"},
    {"name":"Hyoscine Butylbromide 20mg Inj","generic":"Hyoscine Butylbromide","category":"gi","unit":"injection","strength":"20mg"},
    {"name":"Mebeverine 135mg","generic":"Mebeverine","category":"gi","unit":"tablet","strength":"135mg"},
    {"name":"Mebeverine 200mg SR","generic":"Mebeverine","category":"gi","unit":"capsule","strength":"200mg"},
    {"name":"Dicyclomine 10mg","generic":"Dicyclomine","category":"gi","unit":"tablet","strength":"10mg"},
    {"name":"Dicyclomine 10mg/5ml Syrup","generic":"Dicyclomine","category":"gi","unit":"syrup","strength":"10mg/5ml"},
    {"name":"Lactulose 10g/15ml Syrup","generic":"Lactulose","category":"gi","unit":"syrup","strength":"10g/15ml"},
    {"name":"Lactulose 3.3g/5ml Syrup","generic":"Lactulose","category":"gi","unit":"syrup","strength":"3.3g/5ml"},
    {"name":"Bisacodyl 5mg","generic":"Bisacodyl","category":"gi","unit":"tablet","strength":"5mg"},
    {"name":"Bisacodyl 10mg Suppository","generic":"Bisacodyl","category":"gi","unit":"other","strength":"10mg"},
    {"name":"Psyllium Husk 3.5g Sachet","generic":"Psyllium","category":"gi","unit":"other","strength":"3.5g"},
    {"name":"Ursodeoxycholic Acid 150mg","generic":"Ursodeoxycholic Acid","category":"gi","unit":"tablet","strength":"150mg"},
    {"name":"Ursodeoxycholic Acid 300mg","generic":"Ursodeoxycholic Acid","category":"gi","unit":"capsule","strength":"300mg"},
    {"name":"Mesalamine 400mg","generic":"Mesalamine","category":"gi","unit":"tablet","strength":"400mg"},
    {"name":"Mesalamine 800mg","generic":"Mesalamine","category":"gi","unit":"tablet","strength":"800mg"},
    {"name":"Olsalazine 500mg","generic":"Olsalazine","category":"gi","unit":"capsule","strength":"500mg"},

    # ═══════ CARDIOVASCULAR ═══════
    {"name":"Losartan 25mg","generic":"Losartan","category":"cardiovascular","unit":"tablet","strength":"25mg"},
    {"name":"Losartan 50mg","generic":"Losartan","category":"cardiovascular","unit":"tablet","strength":"50mg"},
    {"name":"Losartan 100mg","generic":"Losartan","category":"cardiovascular","unit":"tablet","strength":"100mg"},
    {"name":"Losartan + HCTZ 50/12.5mg","generic":"Losartan + Hydrochlorothiazide","category":"cardiovascular","unit":"tablet","strength":"50/12.5mg"},
    {"name":"Valsartan 80mg","generic":"Valsartan","category":"cardiovascular","unit":"tablet","strength":"80mg"},
    {"name":"Valsartan 160mg","generic":"Valsartan","category":"cardiovascular","unit":"tablet","strength":"160mg"},
    {"name":"Telmisartan 40mg","generic":"Telmisartan","category":"cardiovascular","unit":"tablet","strength":"40mg"},
    {"name":"Telmisartan 80mg","generic":"Telmisartan","category":"cardiovascular","unit":"tablet","strength":"80mg"},
    {"name":"Irbesartan 150mg","generic":"Irbesartan","category":"cardiovascular","unit":"tablet","strength":"150mg"},
    {"name":"Irbesartan 300mg","generic":"Irbesartan","category":"cardiovascular","unit":"tablet","strength":"300mg"},
    {"name":"Candesartan 8mg","generic":"Candesartan","category":"cardiovascular","unit":"tablet","strength":"8mg"},
    {"name":"Enalapril 5mg","generic":"Enalapril","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Enalapril 10mg","generic":"Enalapril","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Lisinopril 5mg","generic":"Lisinopril","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Lisinopril 10mg","generic":"Lisinopril","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Ramipril 2.5mg","generic":"Ramipril","category":"cardiovascular","unit":"tablet","strength":"2.5mg"},
    {"name":"Ramipril 5mg","generic":"Ramipril","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Captopril 25mg","generic":"Captopril","category":"cardiovascular","unit":"tablet","strength":"25mg"},
    {"name":"Amlodipine 2.5mg","generic":"Amlodipine","category":"cardiovascular","unit":"tablet","strength":"2.5mg"},
    {"name":"Amlodipine 5mg","generic":"Amlodipine","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Amlodipine 10mg","generic":"Amlodipine","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Amlodipine + Losartan 5/50mg","generic":"Amlodipine + Losartan","category":"cardiovascular","unit":"tablet","strength":"5/50mg"},
    {"name":"Nifedipine 10mg","generic":"Nifedipine","category":"cardiovascular","unit":"capsule","strength":"10mg"},
    {"name":"Nifedipine 20mg SR","generic":"Nifedipine","category":"cardiovascular","unit":"tablet","strength":"20mg"},
    {"name":"Nifedipine 30mg SR","generic":"Nifedipine","category":"cardiovascular","unit":"tablet","strength":"30mg"},
    {"name":"Metoprolol 25mg","generic":"Metoprolol","category":"cardiovascular","unit":"tablet","strength":"25mg"},
    {"name":"Metoprolol 50mg","generic":"Metoprolol","category":"cardiovascular","unit":"tablet","strength":"50mg"},
    {"name":"Metoprolol 100mg","generic":"Metoprolol","category":"cardiovascular","unit":"tablet","strength":"100mg"},
    {"name":"Metoprolol 5mg Inj","generic":"Metoprolol","category":"cardiovascular","unit":"injection","strength":"5mg"},
    {"name":"Bisoprolol 2.5mg","generic":"Bisoprolol","category":"cardiovascular","unit":"tablet","strength":"2.5mg"},
    {"name":"Bisoprolol 5mg","generic":"Bisoprolol","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Bisoprolol 10mg","generic":"Bisoprolol","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Carvedilol 3.125mg","generic":"Carvedilol","category":"cardiovascular","unit":"tablet","strength":"3.125mg"},
    {"name":"Carvedilol 6.25mg","generic":"Carvedilol","category":"cardiovascular","unit":"tablet","strength":"6.25mg"},
    {"name":"Carvedilol 12.5mg","generic":"Carvedilol","category":"cardiovascular","unit":"tablet","strength":"12.5mg"},
    {"name":"Propranolol 10mg","generic":"Propranolol","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Propranolol 40mg","generic":"Propranolol","category":"cardiovascular","unit":"tablet","strength":"40mg"},
    {"name":"Atorvastatin 5mg","generic":"Atorvastatin","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Atorvastatin 10mg","generic":"Atorvastatin","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Atorvastatin 20mg","generic":"Atorvastatin","category":"cardiovascular","unit":"tablet","strength":"20mg"},
    {"name":"Atorvastatin 40mg","generic":"Atorvastatin","category":"cardiovascular","unit":"tablet","strength":"40mg"},
    {"name":"Rosuvastatin 5mg","generic":"Rosuvastatin","category":"cardiovascular","unit":"tablet","strength":"5mg"},
    {"name":"Rosuvastatin 10mg","generic":"Rosuvastatin","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Rosuvastatin 20mg","generic":"Rosuvastatin","category":"cardiovascular","unit":"tablet","strength":"20mg"},
    {"name":"Simvastatin 10mg","generic":"Simvastatin","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Simvastatin 20mg","generic":"Simvastatin","category":"cardiovascular","unit":"tablet","strength":"20mg"},
    {"name":"Simvastatin 40mg","generic":"Simvastatin","category":"cardiovascular","unit":"tablet","strength":"40mg"},
    {"name":"Gemfibrozil 300mg","generic":"Gemfibrozil","category":"cardiovascular","unit":"capsule","strength":"300mg"},
    {"name":"Gemfibrozil 600mg","generic":"Gemfibrozil","category":"cardiovascular","unit":"tablet","strength":"600mg"},
    {"name":"Fenofibrate 145mg","generic":"Fenofibrate","category":"cardiovascular","unit":"tablet","strength":"145mg"},
    {"name":"Fenofibrate 200mg","generic":"Fenofibrate","category":"cardiovascular","unit":"capsule","strength":"200mg"},
    {"name":"Ezetimibe 10mg","generic":"Ezetimibe","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Aspirin 75mg","generic":"Aspirin","category":"cardiovascular","unit":"tablet","strength":"75mg"},
    {"name":"Aspirin 150mg","generic":"Aspirin","category":"cardiovascular","unit":"tablet","strength":"150mg"},
    {"name":"Aspirin 300mg","generic":"Aspirin","category":"cardiovascular","unit":"tablet","strength":"300mg"},
    {"name":"Clopidogrel 75mg","generic":"Clopidogrel","category":"cardiovascular","unit":"tablet","strength":"75mg"},
    {"name":"Clopidogrel 300mg","generic":"Clopidogrel","category":"cardiovascular","unit":"tablet","strength":"300mg"},
    {"name":"Ticagrelor 60mg","generic":"Ticagrelor","category":"cardiovascular","unit":"tablet","strength":"60mg"},
    {"name":"Ticagrelor 90mg","generic":"Ticagrelor","category":"cardiovascular","unit":"tablet","strength":"90mg"},
    {"name":"Dipyridamole 75mg","generic":"Dipyridamole","category":"cardiovascular","unit":"tablet","strength":"75mg"},
    {"name":"Furosemide 20mg","generic":"Furosemide","category":"cardiovascular","unit":"tablet","strength":"20mg"},
    {"name":"Furosemide 40mg","generic":"Furosemide","category":"cardiovascular","unit":"tablet","strength":"40mg"},
    {"name":"Furosemide 20mg Inj","generic":"Furosemide","category":"cardiovascular","unit":"injection","strength":"20mg"},
    {"name":"Spironolactone 25mg","generic":"Spironolactone","category":"cardiovascular","unit":"tablet","strength":"25mg"},
    {"name":"Spironolactone 50mg","generic":"Spironolactone","category":"cardiovascular","unit":"tablet","strength":"50mg"},
    {"name":"Spironolactone 100mg","generic":"Spironolactone","category":"cardiovascular","unit":"tablet","strength":"100mg"},
    {"name":"Hydrochlorothiazide 25mg","generic":"Hydrochlorothiazide","category":"cardiovascular","unit":"tablet","strength":"25mg"},
    {"name":"Indapamide 1.5mg SR","generic":"Indapamide","category":"cardiovascular","unit":"tablet","strength":"1.5mg"},
    {"name":"Digoxin 0.125mg","generic":"Digoxin","category":"cardiovascular","unit":"tablet","strength":"0.125mg"},
    {"name":"Digoxin 0.25mg","generic":"Digoxin","category":"cardiovascular","unit":"tablet","strength":"0.25mg"},
    {"name":"Digoxin 0.5mg/2ml Inj","generic":"Digoxin","category":"cardiovascular","unit":"injection","strength":"0.5mg/2ml"},
    {"name":"Amiodarone 200mg","generic":"Amiodarone","category":"cardiovascular","unit":"tablet","strength":"200mg"},
    {"name":"Amiodarone 150mg/3ml Inj","generic":"Amiodarone","category":"cardiovascular","unit":"injection","strength":"150mg/3ml"},
    {"name":"Diltiazem 30mg","generic":"Diltiazem","category":"cardiovascular","unit":"tablet","strength":"30mg"},
    {"name":"Diltiazem 60mg","generic":"Diltiazem","category":"cardiovascular","unit":"tablet","strength":"60mg"},
    {"name":"Diltiazem 90mg SR","generic":"Diltiazem","category":"cardiovascular","unit":"capsule","strength":"90mg"},
    {"name":"Verapamil 40mg","generic":"Verapamil","category":"cardiovascular","unit":"tablet","strength":"40mg"},
    {"name":"Verapamil 80mg","generic":"Verapamil","category":"cardiovascular","unit":"tablet","strength":"80mg"},
    {"name":"Verapamil 240mg SR","generic":"Verapamil","category":"cardiovascular","unit":"tablet","strength":"240mg"},
    {"name":"Isosorbide Mononitrate 20mg","generic":"Isosorbide Mononitrate","category":"cardiovascular","unit":"tablet","strength":"20mg"},
    {"name":"Isosorbide Mononitrate 30mg SR","generic":"Isosorbide Mononitrate","category":"cardiovascular","unit":"tablet","strength":"30mg"},
    {"name":"Isosorbide Dinitrate 10mg","generic":"Isosorbide Dinitrate","category":"cardiovascular","unit":"tablet","strength":"10mg"},
    {"name":"Nitroglycerin 0.5mg SL","generic":"Nitroglycerin","category":"cardiovascular","unit":"tablet","strength":"0.5mg"},
    {"name":"Nitroglycerin 5mg Patch","generic":"Nitroglycerin","category":"cardiovascular","unit":"other","strength":"5mg/24h"},

    # ═══════ DIABETES & ENDOCRINE ═══════
    {"name":"Metformin 250mg","generic":"Metformin","category":"diabetes","unit":"tablet","strength":"250mg"},
    {"name":"Metformin 500mg","generic":"Metformin","category":"diabetes","unit":"tablet","strength":"500mg"},
    {"name":"Metformin 850mg","generic":"Metformin","category":"diabetes","unit":"tablet","strength":"850mg"},
    {"name":"Metformin 1g SR","generic":"Metformin","category":"diabetes","unit":"tablet","strength":"1g"},
    {"name":"Metformin 500mg SR","generic":"Metformin","category":"diabetes","unit":"tablet","strength":"500mg SR"},
    {"name":"Glibenclamide 5mg","generic":"Glibenclamide","category":"diabetes","unit":"tablet","strength":"5mg"},
    {"name":"Gliclazide 30mg SR","generic":"Gliclazide","category":"diabetes","unit":"tablet","strength":"30mg"},
    {"name":"Gliclazide 60mg SR","generic":"Gliclazide","category":"diabetes","unit":"tablet","strength":"60mg"},
    {"name":"Gliclazide 80mg","generic":"Gliclazide","category":"diabetes","unit":"tablet","strength":"80mg"},
    {"name":"Glimepiride 1mg","generic":"Glimepiride","category":"diabetes","unit":"tablet","strength":"1mg"},
    {"name":"Glimepiride 2mg","generic":"Glimepiride","category":"diabetes","unit":"tablet","strength":"2mg"},
    {"name":"Glimepiride 3mg","generic":"Glimepiride","category":"diabetes","unit":"tablet","strength":"3mg"},
    {"name":"Glimepiride 4mg","generic":"Glimepiride","category":"diabetes","unit":"tablet","strength":"4mg"},
    {"name":"Metformin + Glibenclamide 500/5mg","generic":"Metformin + Glibenclamide","category":"diabetes","unit":"tablet","strength":"500/5mg"},
    {"name":"Metformin + Glimepiride 500/2mg","generic":"Metformin + Glimepiride","category":"diabetes","unit":"tablet","strength":"500/2mg"},
    {"name":"Pioglitazone 15mg","generic":"Pioglitazone","category":"diabetes","unit":"tablet","strength":"15mg"},
    {"name":"Pioglitazone 30mg","generic":"Pioglitazone","category":"diabetes","unit":"tablet","strength":"30mg"},
    {"name":"Sitagliptin 50mg","generic":"Sitagliptin","category":"diabetes","unit":"tablet","strength":"50mg"},
    {"name":"Sitagliptin 100mg","generic":"Sitagliptin","category":"diabetes","unit":"tablet","strength":"100mg"},
    {"name":"Sitagliptin + Metformin 50/500mg","generic":"Sitagliptin + Metformin","category":"diabetes","unit":"tablet","strength":"50/500mg"},
    {"name":"Vildagliptin 50mg","generic":"Vildagliptin","category":"diabetes","unit":"tablet","strength":"50mg"},
    {"name":"Vildagliptin + Metformin 50/500mg","generic":"Vildagliptin + Metformin","category":"diabetes","unit":"tablet","strength":"50/500mg"},
    {"name":"Saxagliptin 5mg","generic":"Saxagliptin","category":"diabetes","unit":"tablet","strength":"5mg"},
    {"name":"Linagliptin 5mg","generic":"Linagliptin","category":"diabetes","unit":"tablet","strength":"5mg"},
    {"name":"Empagliflozin 10mg","generic":"Empagliflozin","category":"diabetes","unit":"tablet","strength":"10mg"},
    {"name":"Empagliflozin 25mg","generic":"Empagliflozin","category":"diabetes","unit":"tablet","strength":"25mg"},
    {"name":"Dapagliflozin 5mg","generic":"Dapagliflozin","category":"diabetes","unit":"tablet","strength":"5mg"},
    {"name":"Dapagliflozin 10mg","generic":"Dapagliflozin","category":"diabetes","unit":"tablet","strength":"10mg"},
    {"name":"Canagliflozin 100mg","generic":"Canagliflozin","category":"diabetes","unit":"tablet","strength":"100mg"},
    {"name":"Empagliflozin + Metformin 5/500mg","generic":"Empagliflozin + Metformin","category":"diabetes","unit":"tablet","strength":"5/500mg"},
    {"name":"Dapagliflozin + Metformin 5/500mg","generic":"Dapagliflozin + Metformin","category":"diabetes","unit":"tablet","strength":"5/500mg"},
    {"name":"Liraglutide 6mg/ml Inj","generic":"Liraglutide","category":"diabetes","unit":"injection","strength":"6mg/ml"},
    {"name":"Dulaglutide 0.75mg Inj","generic":"Dulaglutide","category":"diabetes","unit":"injection","strength":"0.75mg"},
    {"name":"Dulaglutide 1.5mg Inj","generic":"Dulaglutide","category":"diabetes","unit":"injection","strength":"1.5mg"},
    {"name":"Insulin Regular 40IU/ml","generic":"Insulin Regular","category":"diabetes","unit":"injection","strength":"40IU/ml"},
    {"name":"Insulin Regular 100IU/ml","generic":"Insulin Regular","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin NPH 100IU/ml","generic":"Insulin NPH","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin Mixtard 30/70","generic":"Insulin","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin Mixtard 50/50","generic":"Insulin","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin Glargine 100IU/ml","generic":"Insulin Glargine","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin Detemir 100IU/ml","generic":"Insulin Detemir","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin Aspart 100IU/ml","generic":"Insulin Aspart","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Insulin Lispro 100IU/ml","generic":"Insulin Lispro","category":"diabetes","unit":"injection","strength":"100IU/ml"},
    {"name":"Levothyroxine 25mcg","generic":"Levothyroxine","category":"endocrine","unit":"tablet","strength":"25mcg"},
    {"name":"Levothyroxine 50mcg","generic":"Levothyroxine","category":"endocrine","unit":"tablet","strength":"50mcg"},
    {"name":"Levothyroxine 75mcg","generic":"Levothyroxine","category":"endocrine","unit":"tablet","strength":"75mcg"},
    {"name":"Levothyroxine 100mcg","generic":"Levothyroxine","category":"endocrine","unit":"tablet","strength":"100mcg"},
    {"name":"Levothyroxine 125mcg","generic":"Levothyroxine","category":"endocrine","unit":"tablet","strength":"125mcg"},
    {"name":"Levothyroxine 150mcg","generic":"Levothyroxine","category":"endocrine","unit":"tablet","strength":"150mcg"},
    {"name":"Carbimazole 5mg","generic":"Carbimazole","category":"endocrine","unit":"tablet","strength":"5mg"},
    {"name":"Propylthiouracil 50mg","generic":"Propylthiouracil","category":"endocrine","unit":"tablet","strength":"50mg"},

    # ═══════ TOPICALS & ANTIFUNGALS ═══════
    {"name":"Clotrimazole 1% Cream","generic":"Clotrimazole","category":"antifungal","unit":"cream","strength":"1%"},
    {"name":"Clotrimazole 500mg Pessary","generic":"Clotrimazole","category":"antifungal","unit":"other","strength":"500mg"},
    {"name":"Clotrimazole 100mg Pessary","generic":"Clotrimazole","category":"antifungal","unit":"other","strength":"100mg"},
    {"name":"Miconazole 2% Cream","generic":"Miconazole","category":"antifungal","unit":"cream","strength":"2%"},
    {"name":"Miconazole Oral Gel","generic":"Miconazole","category":"antifungal","unit":"other","strength":"20mg/g"},
    {"name":"Ketoconazole 2% Cream","generic":"Ketoconazole","category":"antifungal","unit":"cream","strength":"2%"},
    {"name":"Ketoconazole 200mg","generic":"Ketoconazole","category":"antifungal","unit":"tablet","strength":"200mg"},
    {"name":"Ketoconazole 2% Shampoo","generic":"Ketoconazole","category":"antifungal","unit":"other","strength":"2%"},
    {"name":"Terbinafine 250mg","generic":"Terbinafine","category":"antifungal","unit":"tablet","strength":"250mg"},
    {"name":"Terbinafine 1% Cream","generic":"Terbinafine","category":"antifungal","unit":"cream","strength":"1%"},
    {"name":"Fluconazole 150mg","generic":"Fluconazole","category":"antifungal","unit":"capsule","strength":"150mg"},
    {"name":"Fluconazole 200mg","generic":"Fluconazole","category":"antifungal","unit":"capsule","strength":"200mg"},
    {"name":"Fluconazole 50mg/5ml Susp","generic":"Fluconazole","category":"antifungal","unit":"syrup","strength":"50mg/5ml"},
    {"name":"Fluconazole 200mg/100ml Inf","generic":"Fluconazole","category":"antifungal","unit":"other","strength":"200mg/100ml"},
    {"name":"Itraconazole 100mg","generic":"Itraconazole","category":"antifungal","unit":"capsule","strength":"100mg"},
    {"name":"Griseofulvin 500mg","generic":"Griseofulvin","category":"antifungal","unit":"tablet","strength":"500mg"},
    {"name":"Nystatin 100,000IU/ml Susp","generic":"Nystatin","category":"antifungal","unit":"syrup","strength":"100000IU/ml"},
    {"name":"Nystatin 100,000IU Pessary","generic":"Nystatin","category":"antifungal","unit":"other","strength":"100000IU"},
    {"name":"Acyclovir 200mg","generic":"Acyclovir","category":"antiviral","unit":"tablet","strength":"200mg"},
    {"name":"Acyclovir 400mg","generic":"Acyclovir","category":"antiviral","unit":"tablet","strength":"400mg"},
    {"name":"Acyclovir 800mg","generic":"Acyclovir","category":"antiviral","unit":"tablet","strength":"800mg"},
    {"name":"Acyclovir 200mg/5ml Susp","generic":"Acyclovir","category":"antiviral","unit":"syrup","strength":"200mg/5ml"},
    {"name":"Acyclovir 5% Cream","generic":"Acyclovir","category":"antiviral","unit":"cream","strength":"5%"},
    {"name":"Acyclovir 250mg Inj","generic":"Acyclovir","category":"antiviral","unit":"injection","strength":"250mg"},
    {"name":"Valacyclovir 500mg","generic":"Valacyclovir","category":"antiviral","unit":"tablet","strength":"500mg"},
    {"name":"Valacyclovir 1g","generic":"Valacyclovir","category":"antiviral","unit":"tablet","strength":"1g"},
    {"name":"Oseltamivir 75mg","generic":"Oseltamivir","category":"antiviral","unit":"capsule","strength":"75mg"},
    {"name":"Mupirocin 2% Ointment","generic":"Mupirocin","category":"antibiotic","unit":"cream","strength":"2%"},
    {"name":"Mupirocin 2% Cream","generic":"Mupirocin","category":"antibiotic","unit":"cream","strength":"2%"},
    {"name":"Fusidic Acid 2% Cream","generic":"Fusidic Acid","category":"antibiotic","unit":"cream","strength":"2%"},
    {"name":"Fusidic Acid 2% Ointment","generic":"Fusidic Acid","category":"antibiotic","unit":"cream","strength":"2%"},
    {"name":"Povidone Iodine 10% Solution","generic":"Povidone Iodine","category":"antiseptic","unit":"other","strength":"10%"},
    {"name":"Povidone Iodine 7.5% Scrub","generic":"Povidone Iodine","category":"antiseptic","unit":"other","strength":"7.5%"},
    {"name":"Silver Sulfadiazine 1% Cream","generic":"Silver Sulfadiazine","category":"antibiotic","unit":"cream","strength":"1%"},
    {"name":"Benzoyl Peroxide 5% Gel","generic":"Benzoyl Peroxide","category":"dermatology","unit":"cream","strength":"5%"},
    {"name":"Tretinoin 0.05% Cream","generic":"Tretinoin","category":"dermatology","unit":"cream","strength":"0.05%"},
    {"name":"Adapalene 0.1% Gel","generic":"Adapalene","category":"dermatology","unit":"cream","strength":"0.1%"},

    # ═══════ EYE & ENT ═══════
    {"name":"Chloramphenicol 0.5% Eye Drops","generic":"Chloramphenicol","category":"eye","unit":"drops","strength":"0.5%"},
    {"name":"Chloramphenicol 1% Eye Ointment","generic":"Chloramphenicol","category":"eye","unit":"cream","strength":"1%"},
    {"name":"Tobramycin 0.3% Eye Drops","generic":"Tobramycin","category":"eye","unit":"drops","strength":"0.3%"},
    {"name":"Moxifloxacin 0.5% Eye Drops","generic":"Moxifloxacin","category":"eye","unit":"drops","strength":"0.5%"},
    {"name":"Ofloxacin 0.3% Eye Drops","generic":"Ofloxacin","category":"eye","unit":"drops","strength":"0.3%"},
    {"name":"Gatifloxacin 0.3% Eye Drops","generic":"Gatifloxacin","category":"eye","unit":"drops","strength":"0.3%"},
    {"name":"Ciprofloxacin 0.3% Eye Drops","generic":"Ciprofloxacin","category":"eye","unit":"drops","strength":"0.3%"},
    {"name":"Olopatadine 0.1% Eye Drops","generic":"Olopatadine","category":"eye","unit":"drops","strength":"0.1%"},
    {"name":"Ketotifen 0.025% Eye Drops","generic":"Ketotifen","category":"eye","unit":"drops","strength":"0.025%"},
    {"name":"Loteprednol 0.5% Eye Drops","generic":"Loteprednol","category":"eye","unit":"drops","strength":"0.5%"},
    {"name":"Prednisolone 1% Eye Drops","generic":"Prednisolone","category":"eye","unit":"drops","strength":"1%"},
    {"name":"Dexamethasone 0.1% Eye Drops","generic":"Dexamethasone","category":"eye","unit":"drops","strength":"0.1%"},
    {"name":"Timolol 0.5% Eye Drops","generic":"Timolol","category":"eye","unit":"drops","strength":"0.5%"},
    {"name":"Latanoprost 0.005% Eye Drops","generic":"Latanoprost","category":"eye","unit":"drops","strength":"0.005%"},
    {"name":"Bimatoprost 0.01% Eye Drops","generic":"Bimatoprost","category":"eye","unit":"drops","strength":"0.01%"},
    {"name":"Travoprost 0.004% Eye Drops","generic":"Travoprost","category":"eye","unit":"drops","strength":"0.004%"},
    {"name":"Brinzolamide 1% Eye Drops","generic":"Brinzolamide","category":"eye","unit":"drops","strength":"1%"},
    {"name":"Dorzolamide 2% Eye Drops","generic":"Dorzolamide","category":"eye","unit":"drops","strength":"2%"},
    {"name":"Artificial Tears 0.5% Eye Drops","generic":"Carboxymethylcellulose","category":"eye","unit":"drops","strength":"0.5%"},
    {"name":"Gentamicin 0.3% Ear Drops","generic":"Gentamicin","category":"ear","unit":"drops","strength":"0.3%"},
    {"name":"Ciprofloxacin + Dexamethasone Ear Drops","generic":"Ciprofloxacin + Dexamethasone","category":"ear","unit":"drops","strength":"0.3/0.1%"},
    {"name":"Clotrimazole 1% Ear Drops","generic":"Clotrimazole","category":"ear","unit":"drops","strength":"1%"},

    # ═══════ SUPPLEMENTS & VITAMINS ═══════
    {"name":"Vitamin B Complex","generic":"Multivitamin B","category":"supplement","unit":"tablet","strength":"-"},
    {"name":"Vitamin B Complex Inj","generic":"Multivitamin B","category":"supplement","unit":"injection","strength":"2ml"},
    {"name":"Vitamin B12 500mcg","generic":"Cyanocobalamin","category":"supplement","unit":"tablet","strength":"500mcg"},
    {"name":"Vitamin B12 1000mcg Inj","generic":"Cyanocobalamin","category":"supplement","unit":"injection","strength":"1000mcg/ml"},
    {"name":"Vitamin D3 2000IU","generic":"Cholecalciferol","category":"supplement","unit":"capsule","strength":"2000IU"},
    {"name":"Vitamin D3 4000IU","generic":"Cholecalciferol","category":"supplement","unit":"capsule","strength":"4000IU"},
    {"name":"Vitamin D3 200,000IU Inj","generic":"Cholecalciferol","category":"supplement","unit":"injection","strength":"200000IU"},
    {"name":"Vitamin D3 600,000IU Inj","generic":"Cholecalciferol","category":"supplement","unit":"injection","strength":"600000IU"},
    {"name":"Vitamin C 250mg","generic":"Ascorbic Acid","category":"supplement","unit":"tablet","strength":"250mg"},
    {"name":"Vitamin C 500mg","generic":"Ascorbic Acid","category":"supplement","unit":"tablet","strength":"500mg"},
    {"name":"Vitamin C 1000mg","generic":"Ascorbic Acid","category":"supplement","unit":"tablet","strength":"1000mg"},
    {"name":"Vitamin E 200IU","generic":"Tocopherol","category":"supplement","unit":"capsule","strength":"200IU"},
    {"name":"Vitamin E 400IU","generic":"Tocopherol","category":"supplement","unit":"capsule","strength":"400IU"},
    {"name":"Vitamin A 10,000IU","generic":"Retinol","category":"supplement","unit":"capsule","strength":"10000IU"},
    {"name":"Multivitamin + Multimineral","generic":"Multivitamin","category":"supplement","unit":"tablet","strength":"-"},
    {"name":"Folic Acid 1mg","generic":"Folic Acid","category":"supplement","unit":"tablet","strength":"1mg"},
    {"name":"Folic Acid 5mg","generic":"Folic Acid","category":"supplement","unit":"tablet","strength":"5mg"},
    {"name":"Ferrous Sulfate 200mg","generic":"Ferrous Sulfate","category":"supplement","unit":"tablet","strength":"200mg"},
    {"name":"Iron Polymaltose Complex","generic":"Iron","category":"supplement","unit":"tablet","strength":"100mg"},
    {"name":"Iron + Folic Acid","generic":"Iron + Folic Acid","category":"supplement","unit":"tablet","strength":"100/0.5mg"},
    {"name":"Iron Syrup","generic":"Ferrous Sulfate","category":"supplement","unit":"syrup","strength":"100mg/5ml"},
    {"name":"Calcium Carbonate 500mg","generic":"Calcium Carbonate","category":"supplement","unit":"tablet","strength":"500mg"},
    {"name":"Calcium + Vitamin D3","generic":"Calcium + Vitamin D3","category":"supplement","unit":"tablet","strength":"500mg+200IU"},
    {"name":"Calcium + Vitamin D3 + Zinc","generic":"Calcium + Vit D3 + Zinc","category":"supplement","unit":"tablet","strength":"500mg+200IU+7.5mg"},
    {"name":"Zinc Sulfate 20mg","generic":"Zinc Sulfate","category":"supplement","unit":"tablet","strength":"20mg"},
    {"name":"Zinc Sulfate Syrup","generic":"Zinc Sulfate","category":"supplement","unit":"syrup","strength":"20mg/5ml"},
    {"name":"Magnesium Oxide 250mg","generic":"Magnesium","category":"supplement","unit":"tablet","strength":"250mg"},
    {"name":"Selenium 50mcg","generic":"Selenium","category":"supplement","unit":"tablet","strength":"50mcg"},
    {"name":"Omega-3 1000mg","generic":"Fish Oil","category":"supplement","unit":"capsule","strength":"1000mg"},
    {"name":"CoQ10 100mg","generic":"Coenzyme Q10","category":"supplement","unit":"capsule","strength":"100mg"},

    # ═══════ IV FLUIDS ═══════
    {"name":"Normal Saline 100ml","generic":"Sodium Chloride 0.9%","category":"iv_fluids","unit":"other","strength":"100ml"},
    {"name":"Normal Saline 250ml","generic":"Sodium Chloride 0.9%","category":"iv_fluids","unit":"other","strength":"250ml"},
    {"name":"Normal Saline 500ml","generic":"Sodium Chloride 0.9%","category":"iv_fluids","unit":"other","strength":"500ml"},
    {"name":"Normal Saline 1000ml","generic":"Sodium Chloride 0.9%","category":"iv_fluids","unit":"other","strength":"1000ml"},
    {"name":"Ringer Lactate 500ml","generic":"Ringer Lactate","category":"iv_fluids","unit":"other","strength":"500ml"},
    {"name":"Ringer Lactate 1000ml","generic":"Ringer Lactate","category":"iv_fluids","unit":"other","strength":"1000ml"},
    {"name":"Dextrose 5% 500ml","generic":"Dextrose","category":"iv_fluids","unit":"other","strength":"5% 500ml"},
    {"name":"Dextrose 5% 1000ml","generic":"Dextrose","category":"iv_fluids","unit":"other","strength":"5% 1000ml"},
    {"name":"Dextrose 10% 500ml","generic":"Dextrose","category":"iv_fluids","unit":"other","strength":"10% 500ml"},
    {"name":"DNS 500ml","generic":"Dextrose + Saline","category":"iv_fluids","unit":"other","strength":"500ml"},
    {"name":"DNS 1000ml","generic":"Dextrose + Saline","category":"iv_fluids","unit":"other","strength":"1000ml"},
    {"name":"Darrow Solution 500ml","generic":"Darrow","category":"iv_fluids","unit":"other","strength":"500ml"},
    {"name":"Isolyte P 500ml","generic":"Pediatric Solution","category":"iv_fluids","unit":"other","strength":"500ml"},
    {"name":"Isolyte M 500ml","generic":"Maintenance Solution","category":"iv_fluids","unit":"other","strength":"500ml"},
    {"name":"Mannitol 20% 500ml","generic":"Mannitol","category":"iv_fluids","unit":"other","strength":"20% 500ml"},

    # ═══════ CNS & PSYCHIATRIC ═══════
    {"name":"Alprazolam 0.25mg","generic":"Alprazolam","category":"cns","unit":"tablet","strength":"0.25mg"},
    {"name":"Alprazolam 0.5mg","generic":"Alprazolam","category":"cns","unit":"tablet","strength":"0.5mg"},
    {"name":"Alprazolam 1mg","generic":"Alprazolam","category":"cns","unit":"tablet","strength":"1mg"},
    {"name":"Lorazepam 1mg","generic":"Lorazepam","category":"cns","unit":"tablet","strength":"1mg"},
    {"name":"Lorazepam 2mg","generic":"Lorazepam","category":"cns","unit":"tablet","strength":"2mg"},
    {"name":"Lorazepam 4mg Inj","generic":"Lorazepam","category":"cns","unit":"injection","strength":"4mg"},
    {"name":"Clonazepam 0.5mg","generic":"Clonazepam","category":"cns","unit":"tablet","strength":"0.5mg"},
    {"name":"Clonazepam 1mg","generic":"Clonazepam","category":"cns","unit":"tablet","strength":"1mg"},
    {"name":"Clonazepam 2mg","generic":"Clonazepam","category":"cns","unit":"tablet","strength":"2mg"},
    {"name":"Diazepam 2mg","generic":"Diazepam","category":"cns","unit":"tablet","strength":"2mg"},
    {"name":"Diazepam 5mg","generic":"Diazepam","category":"cns","unit":"tablet","strength":"5mg"},
    {"name":"Diazepam 10mg","generic":"Diazepam","category":"cns","unit":"tablet","strength":"10mg"},
    {"name":"Diazepam 10mg Inj","generic":"Diazepam","category":"cns","unit":"injection","strength":"10mg"},
    {"name":"Midazolam 7.5mg","generic":"Midazolam","category":"cns","unit":"tablet","strength":"7.5mg"},
    {"name":"Midazolam 15mg","generic":"Midazolam","category":"cns","unit":"tablet","strength":"15mg"},
    {"name":"Midazolam 5mg/5ml Inj","generic":"Midazolam","category":"cns","unit":"injection","strength":"5mg/5ml"},
    {"name":"Zolpidem 10mg","generic":"Zolpidem","category":"cns","unit":"tablet","strength":"10mg"},
    {"name":"Escitalopram 5mg","generic":"Escitalopram","category":"cns","unit":"tablet","strength":"5mg"},
    {"name":"Escitalopram 10mg","generic":"Escitalopram","category":"cns","unit":"tablet","strength":"10mg"},
    {"name":"Escitalopram 20mg","generic":"Escitalopram","category":"cns","unit":"tablet","strength":"20mg"},
    {"name":"Fluoxetine 10mg","generic":"Fluoxetine","category":"cns","unit":"capsule","strength":"10mg"},
    {"name":"Fluoxetine 20mg","generic":"Fluoxetine","category":"cns","unit":"capsule","strength":"20mg"},
    {"name":"Paroxetine 12.5mg","generic":"Paroxetine","category":"cns","unit":"tablet","strength":"12.5mg"},
    {"name":"Paroxetine 20mg","generic":"Paroxetine","category":"cns","unit":"tablet","strength":"20mg"},
    {"name":"Sertraline 50mg","generic":"Sertraline","category":"cns","unit":"tablet","strength":"50mg"},
    {"name":"Sertraline 100mg","generic":"Sertraline","category":"cns","unit":"tablet","strength":"100mg"},
    {"name":"Venlafaxine 37.5mg","generic":"Venlafaxine","category":"cns","unit":"tablet","strength":"37.5mg"},
    {"name":"Venlafaxine 75mg","generic":"Venlafaxine","category":"cns","unit":"tablet","strength":"75mg"},
    {"name":"Venlafaxine 150mg SR","generic":"Venlafaxine","category":"cns","unit":"capsule","strength":"150mg"},
    {"name":"Citalopram 20mg","generic":"Citalopram","category":"cns","unit":"tablet","strength":"20mg"},
    {"name":"Mirtazapine 15mg","generic":"Mirtazapine","category":"cns","unit":"tablet","strength":"15mg"},
    {"name":"Mirtazapine 30mg","generic":"Mirtazapine","category":"cns","unit":"tablet","strength":"30mg"},
    {"name":"Amitriptyline 10mg","generic":"Amitriptyline","category":"cns","unit":"tablet","strength":"10mg"},
    {"name":"Amitriptyline 25mg","generic":"Amitriptyline","category":"cns","unit":"tablet","strength":"25mg"},
    {"name":"Amitriptyline 50mg","generic":"Amitriptyline","category":"cns","unit":"tablet","strength":"50mg"},
    {"name":"Nortriptyline 10mg","generic":"Nortriptyline","category":"cns","unit":"tablet","strength":"10mg"},
    {"name":"Nortriptyline 25mg","generic":"Nortriptyline","category":"cns","unit":"tablet","strength":"25mg"},
    {"name":"Imipramine 25mg","generic":"Imipramine","category":"cns","unit":"tablet","strength":"25mg"},
    {"name":"Haloperidol 2mg","generic":"Haloperidol","category":"cns","unit":"tablet","strength":"2mg"},
    {"name":"Haloperidol 5mg","generic":"Haloperidol","category":"cns","unit":"tablet","strength":"5mg"},
    {"name":"Haloperidol 5mg Inj","generic":"Haloperidol","category":"cns","unit":"injection","strength":"5mg"},
    {"name":"Risperidone 1mg","generic":"Risperidone","category":"cns","unit":"tablet","strength":"1mg"},
    {"name":"Risperidone 2mg","generic":"Risperidone","category":"cns","unit":"tablet","strength":"2mg"},
    {"name":"Risperidone 3mg","generic":"Risperidone","category":"cns","unit":"tablet","strength":"3mg"},
    {"name":"Olanzapine 5mg","generic":"Olanzapine","category":"cns","unit":"tablet","strength":"5mg"},
    {"name":"Olanzapine 10mg","generic":"Olanzapine","category":"cns","unit":"tablet","strength":"10mg"},
    {"name":"Quetiapine 25mg","generic":"Quetiapine","category":"cns","unit":"tablet","strength":"25mg"},
    {"name":"Quetiapine 100mg","generic":"Quetiapine","category":"cns","unit":"tablet","strength":"100mg"},
    {"name":"Quetiapine 200mg","generic":"Quetiapine","category":"cns","unit":"tablet","strength":"200mg"},
    {"name":"Quetiapine 300mg","generic":"Quetiapine","category":"cns","unit":"tablet","strength":"300mg"},
    {"name":"Lithium Carbonate 300mg","generic":"Lithium","category":"cns","unit":"tablet","strength":"300mg"},
    {"name":"Levetiracetam 250mg","generic":"Levetiracetam","category":"cns","unit":"tablet","strength":"250mg"},
    {"name":"Levetiracetam 500mg","generic":"Levetiracetam","category":"cns","unit":"tablet","strength":"500mg"},
    {"name":"Levetiracetam 1000mg","generic":"Levetiracetam","category":"cns","unit":"tablet","strength":"1000mg"},
    {"name":"Topiramate 25mg","generic":"Topiramate","category":"cns","unit":"tablet","strength":"25mg"},
    {"name":"Topiramate 50mg","generic":"Topiramate","category":"cns","unit":"tablet","strength":"50mg"},
    {"name":"Topiramate 100mg","generic":"Topiramate","category":"cns","unit":"tablet","strength":"100mg"},
    {"name":"Lamotrigine 25mg","generic":"Lamotrigine","category":"cns","unit":"tablet","strength":"25mg"},
    {"name":"Lamotrigine 50mg","generic":"Lamotrigine","category":"cns","unit":"tablet","strength":"50mg"},
    {"name":"Lamotrigine 100mg","generic":"Lamotrigine","category":"cns","unit":"tablet","strength":"100mg"},

    # ═══════ OTHER COMMON ═══════
    {"name":"Allopurinol 100mg","generic":"Allopurinol","category":"gout","unit":"tablet","strength":"100mg"},
    {"name":"Allopurinol 300mg","generic":"Allopurinol","category":"gout","unit":"tablet","strength":"300mg"},
    {"name":"Colchicine 0.5mg","generic":"Colchicine","category":"gout","unit":"tablet","strength":"0.5mg"},
    {"name":"Methotrexate 2.5mg","generic":"Methotrexate","category":"immunosuppressant","unit":"tablet","strength":"2.5mg"},
    {"name":"Methotrexate 7.5mg","generic":"Methotrexate","category":"immunosuppressant","unit":"tablet","strength":"7.5mg"},
    {"name":"Hydroxychloroquine 200mg","generic":"Hydroxychloroquine","category":"immunosuppressant","unit":"tablet","strength":"200mg"},
    {"name":"Sulfasalazine 500mg","generic":"Sulfasalazine","category":"gi","unit":"tablet","strength":"500mg"},
    {"name":"Mycophenolate 500mg","generic":"Mycophenolate Mofetil","category":"immunosuppressant","unit":"tablet","strength":"500mg"},
    {"name":"Azathioprine 50mg","generic":"Azathioprine","category":"immunosuppressant","unit":"tablet","strength":"50mg"},
    {"name":"Cyclosporine 100mg","generic":"Cyclosporine","category":"immunosuppressant","unit":"capsule","strength":"100mg"},
    {"name":"Tacrolimus 1mg","generic":"Tacrolimus","category":"immunosuppressant","unit":"capsule","strength":"1mg"},
    {"name":"Tacrolimus 5mg","generic":"Tacrolimus","category":"immunosuppressant","unit":"capsule","strength":"5mg"},
    {"name":"Misoprostol 200mcg","generic":"Misoprostol","category":"gi","unit":"tablet","strength":"200mcg"},
    {"name":"Oxytocin 5IU/ml Inj","generic":"Oxytocin","category":"obstetrics","unit":"injection","strength":"5IU/ml"},
    {"name":"Heparin 5000IU/ml Inj","generic":"Heparin","category":"anticoagulant","unit":"injection","strength":"5000IU/ml"},
    {"name":"Warfarin 1mg","generic":"Warfarin","category":"anticoagulant","unit":"tablet","strength":"1mg"},
    {"name":"Warfarin 3mg","generic":"Warfarin","category":"anticoagulant","unit":"tablet","strength":"3mg"},
    {"name":"Warfarin 5mg","generic":"Warfarin","category":"anticoagulant","unit":"tablet","strength":"5mg"},
    {"name":"Enoxaparin 40mg Inj","generic":"Enoxaparin","category":"anticoagulant","unit":"injection","strength":"40mg"},
    {"name":"Enoxaparin 60mg Inj","generic":"Enoxaparin","category":"anticoagulant","unit":"injection","strength":"60mg"},
    {"name":"Rivaroxaban 10mg","generic":"Rivaroxaban","category":"anticoagulant","unit":"tablet","strength":"10mg"},
    {"name":"Rivaroxaban 15mg","generic":"Rivaroxaban","category":"anticoagulant","unit":"tablet","strength":"15mg"},
    {"name":"Rivaroxaban 20mg","generic":"Rivaroxaban","category":"anticoagulant","unit":"tablet","strength":"20mg"},
    {"name":"Apixaban 2.5mg","generic":"Apixaban","category":"anticoagulant","unit":"tablet","strength":"2.5mg"},
    {"name":"Apixaban 5mg","generic":"Apixaban","category":"anticoagulant","unit":"tablet","strength":"5mg"},
    {"name":"Dalteparin 5000IU Inj","generic":"Dalteparin","category":"anticoagulant","unit":"injection","strength":"5000IU"},
    {"name":"Benzonatate 100mg","generic":"Benzonatate","category":"respiratory","unit":"capsule","strength":"100mg"},
    {"name":"Tranexamic Acid 500mg","generic":"Tranexamic Acid","category":"hemostatic","unit":"tablet","strength":"500mg"},
    {"name":"Tranexamic Acid 500mg Inj","generic":"Tranexamic Acid","category":"hemostatic","unit":"injection","strength":"500mg"},
]

# Diagnostic keywords → medicine categories
DIAGNOSTIC_SUGGESTIONS = {
    "cough": ["respiratory", "antibiotic", "antihistamine"],
    "dry cough": ["respiratory", "antihistamine"],
    "productive cough": ["respiratory", "antibiotic"],
    "fever": ["analgesic", "antibiotic"],
    "high fever": ["analgesic", "antibiotic"],
    "cold": ["antihistamine", "respiratory", "analgesic"],
    "flu": ["analgesic", "antihistamine", "respiratory", "antiviral"],
    "sore throat": ["antibiotic", "analgesic", "respiratory"],
    "throat pain": ["analgesic", "antibiotic"],
    "infection": ["antibiotic", "analgesic"],
    "bacterial": ["antibiotic"],
    "viral": ["analgesic", "antiviral", "antihistamine"],
    "urinary": ["antibiotic", "analgesic"],
    "uti": ["antibiotic", "analgesic"],
    "kidney": ["antibiotic", "cardiovascular"],
    "diarrhea": ["gi", "antibiotic"],
    "constipation": ["gi"],
    "vomiting": ["antiemetic", "gi"],
    "nausea": ["antiemetic", "gi"],
    "headache": ["analgesic"],
    "migraine": ["analgesic", "antiemetic"],
    "pain": ["analgesic"],
    "body pain": ["analgesic"],
    "back pain": ["analgesic", "cns"],
    "joint pain": ["analgesic"],
    "knee pain": ["analgesic"],
    "muscle pain": ["analgesic"],
    "arthritis": ["analgesic", "steroid"],
    "allergy": ["antihistamine"],
    "allergic": ["antihistamine", "respiratory"],
    "rash": ["antihistamine", "antifungal", "antibiotic", "dermatology"],
    "itching": ["antihistamine", "antifungal", "dermatology"],
    "skin": ["antifungal", "antibiotic", "dermatology", "antihistamine"],
    "asthma": ["respiratory", "steroid"],
    "wheezing": ["respiratory", "steroid"],
    "bronchitis": ["antibiotic", "respiratory"],
    "pneumonia": ["antibiotic", "respiratory", "analgesic"],
    "hypertension": ["cardiovascular"],
    "high bp": ["cardiovascular"],
    "blood pressure": ["cardiovascular"],
    "diabetes": ["diabetes"],
    "sugar": ["diabetes"],
    "cholesterol": ["cardiovascular"],
    "lipid": ["cardiovascular"],
    "gastric": ["gi"],
    "acidity": ["gi"],
    "heartburn": ["gi"],
    "ulcer": ["gi", "antibiotic"],
    "gastritis": ["gi"],
    "ibs": ["gi"],
    "anxiety": ["cns"],
    "depression": ["cns"],
    "insomnia": ["cns"],
    "sleep": ["cns", "antihistamine"],
    "dizziness": ["antiemetic", "cardiovascular"],
    "vertigo": ["antiemetic", "cns"],
    "anemia": ["supplement"],
    "weakness": ["supplement"],
    "fatigue": ["supplement"],
    "pregnancy": ["supplement", "antiemetic"],
    "eye": ["eye"],
    "conjunctivitis": ["eye", "antibiotic"],
    "ear": ["ear", "antibiotic"],
    "ear pain": ["analgesic", "antibiotic", "ear"],
    "sinus": ["antibiotic", "respiratory", "analgesic"],
    "sinusitis": ["antibiotic", "respiratory", "analgesic"],
    "tonsillitis": ["antibiotic", "analgesic"],
    "dental": ["analgesic", "antibiotic"],
    "toothache": ["analgesic", "antibiotic"],
    "wound": ["antibiotic", "analgesic", "antiseptic"],
    "injury": ["analgesic"],
    "fracture": ["analgesic", "supplement"],
    "burn": ["antibiotic", "analgesic", "antiseptic"],
    "seizure": ["cns"],
    "epilepsy": ["cns"],
    "fits": ["cns"],
    "typhoid": ["antibiotic", "analgesic"],
    "malaria": ["antibiotic", "analgesic"],
    "dengue": ["analgesic", "antiemetic", "antiviral"],
    "tuberculosis": ["antibiotic", "respiratory", "supplement"],
    "tb": ["antibiotic", "respiratory", "supplement"],
    "hepatitis": ["antiviral", "supplement"],
    "jaundice": ["gi", "supplement"],
    "std": ["antibiotic", "antiviral"],
    "fungal": ["antifungal", "dermatology"],
    "thyroid": ["endocrine"],
    "obesity": ["diabetes", "cardiovascular"],
    "gout": ["gout", "analgesic"],
    "copd": ["respiratory", "steroid"],
    "chest pain": ["cardiovascular", "analgesic"],
    "palpitation": ["cardiovascular", "cns"],
    "stroke": ["cardiovascular", "anticoagulant"],
    "heart attack": ["cardiovascular", "anticoagulant"],
    "angina": ["cardiovascular"],
    "dehydration": ["iv_fluids", "antiemetic"],
    "allergic reaction": ["antihistamine", "steroid"],
    "anaphylaxis": ["steroid", "antihistamine", "respiratory"],
    "menstrual": ["analgesic", "supplement"],
    "pcos": ["endocrine", "diabetes", "supplement"],
}

def seed_medicines(app):
    """Seed the medicines table with common medications."""
    with app.app_context():
        from models import Hospital
        hospitals = Hospital.query.all()
        if not hospitals:
            print("[WARNING] No hospitals found. Skipping medicine seed.")
            return
        
        existing_count = Medicine.query.count()
        if existing_count >= len(MEDICINES):
            print(f"[INFO] Medicines already seeded ({existing_count} records). Skipping.")
            return

        added = 0
        for hospital in hospitals:
            for med in MEDICINES:
                exists = Medicine.query.filter_by(
                    hospital_id=hospital.id,
                    name=med["name"]
                ).first()
                if not exists:
                    m = Medicine(
                        hospital_id=hospital.id,
                        name=med["name"],
                        generic_name=med.get("generic", ""),
                        category=med.get("category", "other"),
                        unit=med.get("unit", "tablet"),
                        strength=med.get("strength", ""),
                        sale_price=med.get("sale_price", 5 if med.get("category") in ["supplement","antihistamine","gi","analgesic"] else 10),
                        stock_quantity=100,
                        min_stock_level=10,
                        status="available",
                        requires_prescription=med.get("category") in ["antibiotic", "cns", "cardiovascular", "steroid", "immunosuppressant", "anticoagulant"]
                    )
                    db.session.add(m)
                    added += 1
        db.session.commit()
        print(f"[SUCCESS] Seeded {added} new medicines across {len(hospitals)} hospital(s). Total: {Medicine.query.count()}")
